services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    links:
      - db
    command: ["npm", "run", "dev"]
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "i-like-lists"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "password"
