# Build stage
FROM node:12.20.1-alpine3.12 AS builder

WORKDIR /src

COPY tsconfig.json .
COPY package-lock.json .
COPY package.json .

RUN npm ci

RUN npm install argon2

COPY components ./components
COPY lib ./lib
COPY pages ./pages
COPY public ./public
COPY styles ./styles
COPY utils ./utils

EXPOSE 3000

CMD ["npm", "run", "dev"]
